# Generated by Django 4.2 on 2025-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото заказа',
                'verbose_name_plural': 'Фотографии заказов',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Заказ принят')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Заказ оплачен исполнителем')),
                ('price_for_executor', models.PositiveIntegerField(default=50, verbose_name='Цена для исполнителя (сом)')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный номер')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
