# Generated by Django 4.2 on 2025-05-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userregion_options'),
        ('orders', '0002_orders_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userregion', verbose_name='Регион заказа'),
        ),
    ]
