# Generated by Django 4.2 on 2025-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_for_executor',
            field=models.PositiveIntegerField(default=50, verbose_name='Цена для исполнителя (сом)'),
        ),
    ]
