# Generated by Django 4.2 on 2025-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/front/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_photo_with_face',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/with_face/'),
        ),
    ]
