# Generated by Django 4.2 on 2025-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_passport_photo_user_passport_back_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregion',
            options={'verbose_name_plural': 'Регион Пользователей'},
        ),
    ]
