# Generated by Django 4.2 on 2025-06-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_executor_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregion',
            options={'verbose_name_plural': 'Регионы пользователей'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.CreateModel(
            name='UserSubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Подрегион (Район)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='users.userregion')),
            ],
            options={
                'verbose_name_plural': 'Подрегионы пользователей',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usersubregion', verbose_name='Подрегион (район)'),
        ),
    ]
